-- Add viral_score_reasoning column to news_items table
-- This stores the explanation of why a particular viral score was assigned

alter table news_items 
add column if not exists viral_score_reasoning text;

-- Add comment to explain the column
comment on column news_items.viral_score_reasoning is 'Explanation of why this viral score was assigned, generated by GPT-4o analysis';
